# Site settings
title: "Adventures in Software Engineering"
author: Frank Di Natale
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://frankd412.github.io" # the base hostname & protocol for your site

# Social media information
contact:
    twitter_username:   "@therapiditalian"
    github_username:    FrankD412
    linkedin_url:       "https://www.linkedin.com/in/francesco-di-natale-08330867/"
    email:              "frank.dinatale1988@gmail.com"

# Build settings
markdown: kramdown

# Navigation options
nav:
    # Name:     html file name
    About:      call-to-action
    Services:   services
    Portfolio:  portfolio
    Contact:    contact-new
